### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by saerose** [naver/egjs-flicking#310]
## Description
General docs are amazing but it would be lovely to have specifics to every framework as I've been trying to use this on a nuxt application with no success due to the lack of information on its implementation. I'm afraid examples on _codesanbox_ are not very useful either when it comes to events.

(All I've been trying to do is render a list of images with an v-for)

**Comment by WoodNeck** [comment]
Hello @saerose!
Thanks for your suggestion, I think that's super neat :)
Actually, we're planning to rework on all our component documentation as they're quite old.
We'll change them from the beginning, like theme or so.
So I think it might be a great time to do your idea!

Also, it is always welcome to ask anything that is hard to implement with Flicking.
If you just tell us what you want to make, we can give you a guide on that.
Thanks.

**Comment by saerose** [comment]
I just wanted to do a simple image carousel with previous and next buttons. I managed to render the images but not succeeded with events. I also have a little doubt, is it posible to control the slides one shows? If it is, can you guide me? I didn't find anything on the subject and I have two different cases on my website where I need to show only one image full width or a "normal" carousel where I have several.

Thanks for the quick response! ✨

**Comment by WoodNeck** [comment]
Can I ask what does "control the slides one shows" means?
Is it like the presentation style "click to next slide" feature?
I'll make a carousel with a buttons demo for you. Looks like we've omitted it while we're making demos.

**Comment by saerose** [comment]
Sure! The "control the slides one shows" simply means that, for example, I have an array with 10 images but I want to show 3 on my carousel and hide the rest to show them when the user slides or clicks to the next button. Is there a way to do that with flicking? I've seen in other carousels the slidesToShow or similar variable names that do that. Thanks!

**Comment by WoodNeck** [comment]
If you're referencing `slidesToShow` option in [slick](https://kenwheeler.github.io/slick/), I'm afraid that Flicking doesn't have such option.
That's because the main idea below Flicking is to preserve the user's UI as possible, not modifying them.
So, showing exactly 3 panels per view is pretty easy. You can just set width about to 33% each to wrapper size.
Here're some examples I've made. I wish I guessed what you want correctly.
- https://codesandbox.io/s/codesandbox-nuxt-9rfg9

slick's `slidesToShow` can be achieved like the example I made.
But if you want `slidesToScroll`, that option is not supported in Flicking atm, unfortunately.
That option's in high priority like I've described on issue #189.
If you want it right away, here's a little hacky way to do it, which also works with `circular` option.
- https://codepen.io/woodneck/pen/NWWRKgM

Sorry for the late answer, It was a really busy day today 🙇

**Comment by saerose** [comment]
Wo! Thanks, I'm gonna try that. ✨
And also thanks for your quick answering, really! ❤️

**Comment by WoodNeck** [comment]
;)
I'll close this issue at the moment.
Feel free to re-open this issue anytime you want.
