### ISSUE TITLE
Invalid height on first render

### ISSUE THREAD

**Issue by tiagocorreiaalmeida** [naver/egjs-flicking#352]
## Description
On the first render the div with the class "eg-flick-viewport" has an invalid height, I'm not sure why this happens, but if you reload the page after the first time it works, probably because something gets cached, the only way to keep reproducing the problem is by forcing a cache clean on each reload, this way you keep seeing the problem on reload
I also tested that if you set a timeout and you tell it to resize it gets the proper height which is good, but I dont want to use this option otherwise the animations I have will look badly

## Steps to check or reproduce
https://x8yet.csb.app/
https://codesandbox.io/s/react-flicking-examples-x8yet

**Comment by WoodNeck** [comment]
Hello, @tiagocorreiaalmeida!
It looks like it doesn't include the image's height when it renders.
That's why it correctly renders on page reload as the image is loaded immediately by cache.
Unfortunately, Flicking doesn't provide such feature about lazyloading.
You can use Flicking's `resize()` to calculate the correct height after the image is loaded.
You can use any other library that supports image lazy loading, or you can use image `onload` event handler.
Also as you're using React, you can check issue #343 about how to use Flicking's methods in React :)

**Comment by tiagocorreiaalmeida** [comment]
@WoodNeck It makes sense :). 
For this situation I believe I can go with the fixed height, somehow I forgot to test that simple step, thanks for your input and time!
