### ISSUE TITLE
ie9 error: object doesn't support property or method 'now'

### ISSUE THREAD

**Issue by nam-kim** [naver/egjs-flicking#36]
version: latest stable ([2.0.3](https://naver.github.io/egjs-flicking/release/latest/dist/flicking.pkgd.js))
raf polyfill calls window.performance.now, which is not supported in [ie9](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now)

**Comment by netil** [comment]
@nam-kim @thanks for the report.
egjs-flicking since the beginning, the support for IE officially was 10 and above version.
(It doesn't mean that officially supporting for lower IE, even worked in the previous version.)
- https://github.com/naver/egjs/blob/1.0.0/src/flicking.js#L30

Sorry for the wrong description on readme. I'll fix that soon.

**Comment by sculove** [comment]
@netil axes is fixed 
https://github.com/naver/egjs-axes/pull/68
you should use eg.Axes 2.2.0+

**Comment by netil** [comment]
@nam-kim, update to `2.1.0` version. 
- https://github.com/naver/egjs-flicking/releases/tag/2.1.0
