### ISSUE TITLE
Library fails to initialize with version 3.4.7

### ISSUE THREAD

**Issue by bskrypnyk** [naver/egjs-flicking#367]
## Description

When including this resource:
https://cdnjs.cloudflare.com/ajax/libs/egjs-flicking/3.4.7/flicking.js
the library fails to initialize, producing this error in the console:

Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (VM28501 flicking.js:44)
    at VM28501 flicking.js:4071
    at VM28501 flicking.js:4994
    at VM28501 flicking.js:12
    at VM28501 flicking.js:13

__extends @ VM28501 flicking.js:44
(anonymous) @ VM28501 flicking.js:4071
(anonymous) @ VM28501 flicking.js:4994
(anonymous) @ VM28501 flicking.js:12
(anonymous) @ VM28501 flicking.js:13
pen.js:221 Uncaught TypeError: eg.Flicking is not a constructor
    at VM28502 pen.js:6

## Steps to check or reproduce

The provided codepen example with the cdn script set to:

https://cdnjs.cloudflare.com/ajax/libs/egjs-flicking/3.4.7/flicking.js

https://codepen.io/tourist604/pen/qBZaKRw

See console for errors.

**Comment by WoodNeck** [comment]
Hello @bskrypnyk!
Flicking has dependencies that are not included in `flicking.js` script.
So the error indicates that dependencies needed are not defined on the global scope.
In order to include that, you can use our dependency-packaged version: https://cdnjs.cloudflare.com/ajax/libs/egjs-flicking/3.4.7/flicking.pkgd.js
Please change the script src to above URL and the error will be gone :)

**Comment by bskrypnyk** [comment]
Ah yes, that works -- thank you!

May be a good idea to update the instructions in the github README:

to quote:

Installation
Browser
<script src="https://cdnjs.cloudflare.com/ajax/libs/egjs-flicking/3.x.x/flicking.js"></script>

Thank you for the great library!

Cheers!
