### ISSUE TITLE
Window alert is called twice when `renderOnlyVisible` is off

### ISSUE THREAD

**Issue by buckets24** [naver/egjs-flicking#440]
## Description
Window alert is called twice when `renderOnlyVisible` is off.

Is there a way to just display the alert in Panel/Cloned Panel without triggering the alert in Panel/Cloned Panel, so it will just show a single window.alert? Thank you.

**Comment by WoodNeck** [comment]
Hello, @buckets24!
I guess you're using a framework like React, and using `componentDidMount` or something to trigger the alert?
Unfortunately, as all panels are cloned it is impossible to do that.

If it's applicable, you can try using one of the Flicking's events to trigger `window.alert`.

This behavior will be fixed in v4, and will not generate cloned panels anymore.

**Comment by buckets24** [comment]
@WoodNeck yes I am using React and to trigger window.alert I used pusherjs. I encountered window.alert twice because of the cloned panel right?

**Comment by WoodNeck** [comment]
That's right.
