### ISSUE TITLE
[질문] 3.x 대비 4.x의 장점은?

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-flicking#472]

**Comment by WoodNeck** [comment]
안녕하세요. 핵심 내용을 공유드리면 다음과 같습니다.

이번 메이저 업데이트는 기존의 다음과 같은 문제점들을 해결하기 위해서 개발되었습니다.

#### 1. Flicking이 추가하는 CSS로 인한 간섭을 최소화하고, 서버사이드 렌더링(SSR)을 좀 더 원활하게 지원할 수 있도록 했습니다.
기존 Flicking의 기본 동작은 JS 컴포넌트에서 DOM 엘리먼트와, CSS를 자동으로 추가하였기 때문에 스크립트 마운팅 전후로 UI가 달라지는 고질적인 문제가 있었습니다.
또한, CSS의 `position: absolute` 속성을 사용했기 때문에, % 기반 크기를 사용하는 경우 내부 콘텐츠의 크기에 따라 패널의 크기를 자동으로 조절할 수 없는 문제도 존재하였습니다.
특히나, 디자인 - 마크업 - 스크립트를 담당하는 개발자가 서로 다를 경우 스크립트 마운트 전후로 UI가 달라지는 문제가 발생할 수 있기 때문에 스크립트 담당 개발자가 고려해야 하는 일이 더 많았습니다.

- Flicking이 더 이상 DOM 엘리먼트를 자동으로 생성하지 않습니다.
  - 이 변경사항은 Vanilla(Native) Javascript 환경만을 대상으로 하며, 기존 프레임워크(React, Vue, ...) 사용자분들은 기존과 동일하게 사용하실 수 있습니다.
  - 다음과 같이 `flicking-viewport`와 `flicking-camera`의 클래스를 갖는 엘리먼트를 추가해주셔야 합니다.
    ```diff
    <!-- 기존의 경우 단 하나의 엘리먼트만을 필요로 했습니다. -->
    -<div id="element-to-init-flicking">...</div>
    <!-- Flicking v4부터는 다음과 같은 DOM 구조를 필요로 합니다 -->
    +<div class="flicking-viewport">
    +  <div class="flicking-camera">
        ...
    +  </div>
    +</div>
    ```
- 마찬가지로, 더 이상 CSS를 JS 내에서 주입하지 않습니다.
  - 대신에, Flicking에서 2개의 CSS 파일을 제공합니다.
  - `flicking.css`
    - `display: flex` 기반의 CSS 파일로, IE10 이상을 지원합니다.
    - 번들러를 사용하시는 경우, 다음과 같이 import하여 사용하실 수 있습니다.
        ```js
        import "@egjs/flicking/dist/flicking.css";
        ```
  - `flicking-inline.css`
    - `display: inline-block` 기반의 CSS 파일로, 추가적으로 IE9를 지원하실 필요가 있을 때 사용하실 수 있습니다.
    - inline-block의 특성상, 패널간의 간격을 없애기 위해 `font-size: 0` 속성이 추가적으로 사용되므로 폰트 크기가 패널 내에서 초기화되기 때문에 주의하셔서 사용하실 필요가 있습니다.
    - 번들러를 사용하시는 경우, 다음과 같이 import하여 사용하실 수 있습니다.
        ```js
        import "@egjs/flicking/dist/flicking-inline.css";
        ```

#### 2. 더 이상 패널 엘리먼트를 복제하지 않습니다.
연속된 carousel UI를 생성하기 위해서 사용하는 `circular` 옵션은, 기존에는 패널 엘리먼트를 복제하여 루프하는 방식을 사용했습니다.
이 방식은 패널의 수와 크기가 부족한, 즉 어떠한 경우에라도 사용할 수 있다는 장점이 존재하지만
하나의 패널에 콘텐츠가 다수 존재하는 네이버 메인 페이지의 경우나 패널 내부에서 ajax 요청이 발생할 경우 중첩되어 발생될 수 있는 문제가 있습니다.
때문에, Flicking v4부터는 이와 같은 동작을 변경하여, 패널 복제를 없애고 패널이 충분히 있을 때만 circular 옵션을 사용할 수 있도록 변경하였습니다.

#### 3. Promise를 사용합니다.
패널 이동 관련 메소드(`prev`, `next`, `moveTo`)와 내부 패널 엘리먼트 렌더링 작업에 Promise를 사용합니다.
때문에, IE 환경에서 사용하시기 위해서는 ES6 Promise polyfill을 필요로 합니다.

- 이동 관련 메소드의 경우, 해당 패널에 도달했을 경우에만 Promise가 resolve됩니다.
  - 가령, 도중에 사용자의 마우스/터치 입력으로 인해 애니메이션이 중지되었을 경우 reject됩니다.

#### 4. 구조 변경을 통해 커스터마이징을 좀 더 쉽게 할 수 있도록 변경하였습니다.
Flicking을 개조하여 독특한 UI를 사용하시고자 할 때 활용하실 수 있도록 내부 컴포넌트에 대한 접근자와 문서를 추가했습니다.

#### 5. 데모 및 문서 페이지를 개편했습니다.
- 옵션 값에 따른 차이를 쉽게 확인하실 수 있습니다.
- 각 프레임워크별 튜토리얼을 추가했습니다.
- Flicking으로 만들 수 있는 UI들의 예시를 데모 페이지에서 확인하실 수 있습니다.
- [데모 페이지](https://naver.github.io/egjs-flicking/)

#### 추가 옵션/이벤트
##### 추가 옵션
- preventClickOnDrag (기본값: true)
  - 패널 내부에 앵커 태그(\<a\>)와 같이 클릭에 반응하는 엘리먼트의 경우 패널 드래그시에 클릭이 되어 다른 페이지로 넘어가게 됩니다.
  - 이 옵션을 활성화할 경우 해당 동작을 막는 효과가 있습니다.
- disableOnInit (기본값: false)
  - Flicking을 사용자의 입력이 아닌 메소드 / 플러그인으로만 조작하시고자 하는 경우 이 옵션을 활성화하시면 됩니다.
  - 활성화할 경우 초기화시에 자동으로 `disableInput()` 메소드를 호출합니다.
- autoInit (기본값: true)
  - 이제 Flicking을 자동으로 초기화할지 여부를 선택할 수 있습니다.
  - 이 옵션을 false로 주고, 이후에 `init()` 메소드를 호출하여 원하는 타이밍에 Flicking을 초기화 가능합니다.

##### 추가 이벤트
- ready
  - Flicking 초기화시에 트리거되는 이벤트입니다.
- beforeResize
  - 패널 및 뷰포트의 크기를 갱신하는 resize 전에 트리거되는 이벤트입니다.
  - 이 이벤트 시점에 패널의 크기를 변경하면 resize시에 변경된 패널의 크기가 적용됩니다.
- changed/restored
  - 기존에는 인덱스 변경이 `moveEnd` 시점에 이루어졌지만, 좀 더 명확히 타이밍을 구분하기 위해 해당 이벤트를 추가했습니다.
- reachEdge
  - Flicking이 이동 가능한 영역의 시작/끝 지점에 도달했을 때 트리거되는 이벤트입니다.
- panelChange
  - 패널 추가/제거시 트리거되는 이벤트입니다.

##### 추가 프로퍼티
- 옵션이 전부 Flicking의 getter/setter로 추가됩니다.
  - 옵션을 동적으로 변경 가능하게 되었습니다.
- initialized
  - Flicking 초기화 여부를 나타내는 값입니다.
- circularEnabled
  - `circular` 옵션 사용시, 현재 루프가 가능한지 여부를 나타내는 값입니다.
- 기존 `getIndex()`, `getElement()`와 같은 getter 메소드들이 프로퍼티로 변경되었습니다.
  - `index`, `element`로 동일한 값에 접근 가능합니다.

여기에 추가로, 2개의 플러그인을 추가 지원할 예정입니다 (아직 배포되진 않았습니다)
- Arrow
![image](https://user-images.githubusercontent.com/26213435/123889790-28078980-d991-11eb-912e-d3ac6cbdf43d.png)

- Pagination
![image](https://user-images.githubusercontent.com/26213435/123889815-32298800-d991-11eb-9b1a-d4eceed80aaf.png)

---

This major update was developed to solve the following problems.

#### 1. It minimizes interference from the CSS that Flicking adds, and enables more seamless support for server-side rendering (SSR).
The basic behavior of the previous Flicking was that the DOM element and CSS were automatically added from the JS component, so there was a chronic problem that the UI can change before and after the script mounting.
In addition, since we used the `position:absolute` property of the CSS, there was a problem that the panel could not be resized automatically depending on the size of the internal content when using the %-based size.

- Flicking no longer automatically generates DOM elements.
  - This change is intended for Vanilla (Native) Javascript environments only, and existing frameworks (React, Vue, ...) users can use the same.
  - You need to add an element that has the classes of "flicking-viewport" and "flicking-camera" as follows.
    ```diff
    <!-- Previously, only one element was required. -->
    -<div id="element-to-init-flicking">...</div>
    <!-- In Flicking v4, the following DOM structure is required. -->
    +<div class="flicking-viewport">
    +  <div class="flicking-camera">
        ...
    +  </div>
    +</div>
    ```
- Similarly, CSS is no longer injected within JS.
  - Instead, Flicking provides two CSS files.
  - `flicking.css`
    - CSS file based on `display:flex`, which supports IE10 or higher.
    - If you use a bundler, you can import it as follows:
        ```js
        import "@egjs/flicking/dist/flicking.css";
        ```
  - `flicking-inline.css`
    - It is a CSS file based on `display: inline-block` that can be used when IE9 needs to be supported.
    - Due to the nature of the inline-block, the `font-size: 0` property is additionally used to eliminate the gap between panels, so the font size is initialized within the panel, so you need to be careful when using it.
    - If you use a bundler, you can import it as follows:
        ```js
        import "@egjs/flicking/dist/flicking-inline.css";
        ```

#### 2. The panel elements are no longer cloned.
The `circular` option used to create a continuous carousel UI was previously used to clone and loop panel elements.
This approach lacks the number and size of panels, i.e., it can be used in any case.
But when there're many contents exist on one panel, or if ajax request occurs inside the panel, there is a problem that can be caused by clones.
Therefore, we changed this behavior to eliminate panel clones and use the circular option only when there are enough panels.

#### 3. Promise
We're now using Promise for methods like `prev`, `next`, `moveTo` and render method of internal panel elements.
Therefore, ES6 Promise polyfill is required for use in IE environment.

- For the move-related method, Promise is resolved only when the corresponding panel is reached.
- For example, if the animation is stopped due to user's mouse/touch input on the way, it will be rejected.

#### 4. More easier customization
We have added accessors and documents for internal components so that you can modify Flicking to use unique UI.

#### 5. New Demo & API docs page
- You can easily check the differences depending on the option value at the options page.
- Added tutorials for each frameworks.
- [Demo](https://naver.github.io/egjs-flicking/)

#### New Options & Events
##### new Options
- preventClickOnDrag (default: true)
  - For elements that respond to clicks, such as anchor tags (\<a\>) inside the panel, they can be clicked at panel drag and passed to another page.
  - Activating this option has the effect of preventing that behavior.
- disableOnInit (default: false)
  - If you want to disable user input on initializtion, you can activate this option.
  - When enabled, it automatically calls the `disableInput()` method upon initialization.
- autoInit (default: true)
  - You can now choose whether to automatically initialize Flicking.
  - Give this option false, and then call the `init()` method to initialize Flicking at the desired timing.

##### New Events
- ready
  - The event that is triggered when Flicking is initialized.
- beforeResize
  - Events triggered before resize to update the size of panels and viewports.
  - If you change the panel size at the time of this event, the changed panel size will take effect at the time of resize.
- changed/restored
  - Previously, index changes were made at the time of `moveEnd`, but the event was added to distinguish the timing more clearly.
- reachEdge
  - The event that triggers when Flicking reaches the start/end point of the movable area.
- panelChange
  - Events triggered when adding/removing panels.

##### New Properties
- All options will be added as getter/setter for Flicking.
  - The option has become dynamically changeable.
- initialized
  - Value indicating whether Flicking is initialized.
- circularEnabled
  - Value indicating whether the current loop is possible when using the `circle` option.
- Existing getter methods such as `getIndex()` and `getElement()` have been changed to properties.
  - The same value can be accessed with `index` and `element`.

**Comment by changdongchun** [comment]
팀내공유하여 널리 알리겠습니다. 감사합니다.
