### ISSUE TITLE
플리킹 & 이전/다음 탐색 버튼을 함께 지원하는 UI 에서 Animation is interrupted by user input. 에러 발생 문의

### ISSUE THREAD

**Issue by geguriyj** [naver/egjs-flicking#473]
## Description

egjs-flicking & 이전/다음 탐색 버튼을 함께 지원하는 UI 에서 Animation is interrupted by user input. 에러가 발생하여 문의드립니다.
플리킹 동작과 이전/다음 (moveTo/prev/next 를 사용하고 있음) 동작을 번갈아 수행하는 경우 재현됩니다.
egjs-flicking 쇼케이스 샘플에서도 재현이 되고 있어요.
https://naver.github.io/egjs-flicking/Showcases/

이전/다음 버튼에서는 animating 상태 값으로 방어 처리를 했으나,
플리킹 동작에서는 처리 할 수 있는 구간이 없어서 문의드립니다.

flicking.esm.js:282 Uncaught (in promise) FlickingError: Animation is interrupted by user input.

## Steps to check or reproduce

https://naver.github.io/egjs-flicking/Showcases/

**Comment by WoodNeck** [comment]
Hello @geguriyj!
It is expected behavior, as `prev`/`next`/`moveTo` should be resolved only when Flicking reaches the target panel.
It can be easily bypassed like this:
```js
// Simple
flicking.next().catch(() => void 0);

// If you want to be more precise
flicking.next()
  .catch(err => {
    if (err instanceof FlickingError) return;
    throw err;
  });
```

---

안녕하세요, `prev`/`next`/`moveTo` 메소드는 해당 패널에 도착했을 때에만 resolve되며, 그 이외의 경우 관련 이유와 함께 reject됩니다.
관련 에러 메시지를 표시하고 싶지 않으실 경우, 간단히 위의 `.catch(() => void 0)` 구문을 추가해주시면 됩니다.
