### ISSUE TITLE
@egjs/react-flicking  에서 remove 메서드 호출시 Flicking Error 발생에 대한 질문입니다. 

### ISSUE THREAD

**Issue by JOOHOJANG** [naver/egjs-flicking#475]
## Description
`react-flicking` 에서 `remove` 메서드 사용했을 때 패널이 제거되지 않는 에러 문의드립니다. 
`remove` 메서드 사용해서 패널을 제거하려고 하면 `This behavior is not allowed in the frameworks like React, Vue, or Angular` 라는 플리킹 에러가 발생합니다.

위 프레임워크에서는 `remove` 메서드 자체를 사용할 수 없는건가요?? 
만약 그렇다면 권장하시는 패널 삭제 방법이 있는지 궁금합니다.

**Comment by WoodNeck** [comment]
Hello @JOOHOJANG!
Adding/removing panels relies on the framework side because when used in the framework, overlapping the rendering method and the rendering process inside Flicking can result in errors.
Therefore, you can remove the panel by removing the React element inside the <Flicking> tag.

---

안녕하세요, 프레임워크에서 사용시에는 프레임워크의 렌더링 메소드와 Flicking 내부의 렌더링 과정이 겹칠 경우 오류가 발생할 수 있기 때문에 패널 추가/제거 방식은 프레임워크쪽을 의존하고 있습니다.
때문에,<Flicking> 태그 내부의 React 엘리먼트를 제거하는 방식으로 패널을 제거하실 수 있습니다.
가령 예를 들면, list rendering을 사용하실 경우 해당 list 내에서 아이템을 삭제하거나
혹은 조건부 렌더링을 이용하실 수 있습니다.

```jsx
// remove element from "list"
<Flicking>
  { list.map(() => <div></div>) }
</Flicking>

// Or, use conditional rendering
<Flicking>
  { some_condition && <div></div> }
</Flicking>
```
