### ISSUE TITLE
bound=true + align="prev" with few children not working correctly

### ISSUE THREAD

**Issue by matthewlein** [naver/egjs-flicking#505]
## Description
When you have a small number of children and the settings `bound={true}` and `align="prev"`, the carousel allows advancing beyond the bound edge. When the number of children is less than a full viewport, it should not advance at all.

## Steps to check or reproduce
Example:
https://codesandbox.io/s/nice-cannon-hhio5?file=/src/App.tsx

**Comment by WoodNeck** [comment]
Hello @matthewlein! Thanks for the detailed example!
Actually, it is expected behavior because `bound` can be enabled only when the child panel size sum exceeds viewport size.
But yeah, maybe it should be reconsidered because sometimes it is hard to fill the viewport size like the case you gave.
I'll discuss it with our team :)

**Comment by matthewlein** [comment]
OK, sounds good. Hopefully everyone agrees, I think it leads to a kind of confusing user experience especially with the arrow plugin, the arrow is active, and it advances the carousel, but there are no new panels to see.

**Comment by matthewlein** [comment]
Here is the arrow example: https://codesandbox.io/s/determined-black-91oen?file=/src/App.tsx

**Comment by WoodNeck** [comment]
@matthewlein Hello! I've fixed this issue in version 4.2.2 :)
Please try that!

**Comment by matthewlein** [comment]
😍  Love it!

Thanks so much for the quick turnaround. Very happy to have a flexbox based carousel meeting all my needs.
