### ISSUE TITLE
Moving multiple Flicking instances creates disappearing panels

### ISSUE THREAD

**Issue by aniviveCameron** [naver/egjs-flicking#597]
## Description
I have 3 circular Flicking instances, dragging in sync, where the middle one moves the opposite direction of the others. Initially it seems to be working correctly, but after you drag a few panels down, the new panels disappear. 

## Steps to check or reproduce
This function sets the position of the other 2 Flicking not being dragged. It is called with the onMove function.

https://user-images.githubusercontent.com/75447489/144155858-1ea0c6ee-3351-496d-9d91-c2418ad882c0.mov

`   
 const lastPosition: Array<number> = [];
  const isEven = (key: number) => !(key % 2);

const handleWrapping = (flickingEvent: any, key: number) => {
    if (animating && !flickingEvent.isTrusted) {
      return;
    }
    animating = true;
    const position = (flickingArray.current[key].camera as CircularCamera).position;
    const moveBy = (lastPosition[key] || position) - position;

    flickingArray.current.forEach((carousel: Flicking, index: number) => {
      if (key !== index) {
        const moveWithCurrent = isEven(key) !== isEven(index);
        const eachPosition = (carousel.camera as CircularCamera).position;

        const newPos = eachPosition + (moveWithCurrent ? moveBy : moveBy * -1);
        (carousel.camera as CircularCamera).lookAt(newPos);

        setTimeout(() => {
          animating = false;
        }, 1);
      }
    });
    lastPosition[key] = position;
  };
`

**Comment by WoodNeck** [comment]
Hello @aniviveCameron!
It looks like the panels are not toggled to the correct position.
When using the `camera.lookAt` method there's one restriction that the position should be within the camera range.
Normally when using the mouse/touch input, our internal component will do it automatically
But, you can modify the position yourself to put it inside the camera range if you're using the `lookAt`

The fix is simple:
```ts
import { circulatePosition } from "@egjs/flicking";
// Or, if you're using our umd bundle. it's "Flicking.circulatePosition"

const newPos = eachPosition + (moveWithCurrent ? moveBy : moveBy * -1);

const camRange = carousel.camera.range;
const correctPos  = circulatePosition(newPos, camRange.min, camRange.max);
```
I think that can fix the issue, tell me if it doesn't

By the way, that UI looks amazing :)

**Comment by aniviveCameron** [comment]
Thank you so much @WoodNeck ! It worked perfectly!

Thanks!
