### ISSUE TITLE
Fix on 3.9.1 made the whole page freeze (relative issue: #616)

### ISSUE THREAD

**Issue by kazvaggos** [naver/egjs-flicking#624]
"@egjs/vue-flicking": "3.8.1"
## Description
Hello team. Thanks a lot for the fix! 
However, this fix introduced a much bigger bug. When the scenario of the [#616](https://github.com/naver/egjs-flicking/issues/616) happen, then the whole page freezes due to some endless loop happening next.
After debugging it, we noticed that `panel0OnFirstScreen` equals to `NaN` due to `0/0 division` because all the variables on the right hand side equal to 0. This makes the `cloneCount` to equal to `NaN`, creating a domino effect afterwards with endless loops.
![image](https://user-images.githubusercontent.com/29608027/153613245-4c432fc3-5bf2-44ff-9c6f-744cbead771b.png)

A suggested fix that seemed to resolve the domino effect is to add a fallback on `cloneCount`, but we are not sure if this is the correct one.
![image](https://user-images.githubusercontent.com/29608027/153613834-6d8efc60-4f4a-4a06-bcfa-27eb93d7588c.png)

We were forced to downgrade to `"@egjs/vue-flicking": "3.8.0"` with `egjs-flicking: 3.9.0`, because the error that was thrown in the previous version saves as from the whole page to freeze.

**Comment by WoodNeck** [comment]
Hello @kazvaggos!
It's my fault that I was a bit haste to release #619. I should add some more tests or so.
I'll fix this right away :)

**Comment by WoodNeck** [comment]
Can you try this version? `3.8.2-beta.0`
You can install it with

```sh
npm i @egjs/vue-flicking@beta-3
```

**Comment by kazvaggos** [comment]
Hello @WoodNeck ! Thank you for the immediate response.
Now the page doesn't not freeze. However, when the scenario in [#616](https://github.com/naver/egjs-flicking/issues/616) happen, the carousel becomes unresponsive. It only shows the last photo and swiping between photos does not work at all. It is like the carousel has not initialized at all.

**Comment by WoodNeck** [comment]
@kazvaggos 
I think I should take a look at actually what's happening in this case.
Can you provide me with a way to reproduce that issue?
Any of the following methods are appreciated:
- An explanation of how to reproduce the issue
- A simple demo with a Codepen
- URL to your website page, if it's public

**Comment by kazvaggos** [comment]
Hello @WoodNeck .
I created this [pen](https://codepen.io/kazvaggos/pen/QWOOMzb) that simulates the scenario [#619](https://github.com/naver/egjs-flicking/pull/619)
By clicking the button, the flicking component mounts, but sometimes doesn't mount correctly and it is inactive showing only the last photo.
Most probably, it will happen using safari browser. But with chrome, can happen too.

**Comment by WoodNeck** [comment]
@kazvaggos 
That super helped! I found the cause and here's the thing:

When Flicking's initialized before the images are loaded, the panels inside Flicking have 0 sizes and end up stuck in one position.
And that makes Flicking show only the last photo.

Flicking offers `resizeOnContentsReady` to overcome these kinds of issues, but looks like it isn't compatible with frameworks like Vue in the old v3. Panel sizes are fixed correctly, but as cloned panels are not generated so other error still occurs.
Calling `$forceUpdate` can fix that, but v3 doesn't offer any correct timing for it, and we're not adding any more APIs in v3 as we're focusing on v4.

Check this demo, which I've slightly modified from your pen. Init Flicking and clicking force update after it will make the carousel work properly.
- https://codepen.io/woodneck/pen/LYOeYyY

I'll try to fix this, but I suggest using v4 as all kinds of these issues are already fixed in it.

**Comment by WoodNeck** [comment]
I've just released a new version (flicking 3.9.2, vue-flicking 3.8.2) that fixes this issue.
Please try that :)

**Comment by kazvaggos** [comment]
Looks great! Thanks a lot @WoodNeck :muscle:
