### ISSUE TITLE
why was absolute progress removed from 4.x.x

### ISSUE THREAD

**Issue by marko-mlinarevic** [naver/egjs-flicking#866]
## Description
why was absolute progress removed from 4.x.x?

**Comment by malangfox** [comment]
Hello @marko-mlinarevic.

If it's the `progress` property of the `move` event that you're referring to in your issue, it looks like it was removed because it was difficult to ensure stable behavior in all situations.

However, in the general case, a similar implementation could be possible using the `move` event and status of Flicking.

If you want to use `progress` in version 4, perhaps we can leave an example demo to implement the `progress` property.
